name: go

on:
- push
- pull_request

jobs:
  lint:
    strategy:
      matrix:
        platform: [ubuntu-22.04]
        go-version: [1.21.x, 1.x]
    runs-on: ${{ matrix.platform }}
    name: Linters (Static Analysis) for Go
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Linting & vetting.
        run: make lint
  test:
    strategy:
      matrix:
        platform: [ubuntu-22.04]
        go-version: [1.21.x, 1.x]
    runs-on: ${{ matrix.platform }}
    name: integration tests
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Check out code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go.
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install ffmpeg
        run: |
            sudo apt-get update
            sudo apt-get install ffmpeg

      - name: Run tests
        run: make test-integration

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: coverage.out
